# Manuell geändert am 2025-03-27

services:
  # === Backend (Node.js/Express) ===
  - type: web
    name: smartfridge-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: cd smafri/backend && node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://monikaphm511:1Wftx8F5vyUst7uX@smartfridge0.2twexph.mongodb.net/smartfridge?retryWrites=true&w=majority&appName=smartfridge0
      - key: NODE_ENV
        value: production


#nun wieder static_site

  # === Frontend (Angular Static Hosting) ===
  - type: static_site
    name: smartfridge-frontend
    env: static
    buildCommand: npm install && npx ng build --configuration production
    publishDir: smafri/dist/smafri
    staticPublishOptions:
      fallback: index.html

#hoffentlich klappts
