services:
  # === Backend (Node.js/Express) ===
  - type: web
    name: smartfridge-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: cd smafri/backend && node server.js
    rootDir: smafri/backend
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://monikaphm511:1Wftx8F5vyUst7uX@smartfridge0.2twexph.mongodb.net/smartfridge?retryWrites=true&w=majority&appName=smartfridge0
      - key: NODE_ENV
        value: production

  # === Frontend (Angular Static Hosting) ===
  - type: static
    name: smartfridge-frontend
    env: static
    buildCommand: npm install && npx ng build --configuration production
    publishDir: smafri/dist/smafri
    staticPublishOptions:
    fallback: index.html
   
